# We require newer versions of the Serverless framework.
frameworkVersion: ">=1.21.0 <2.0.0"

plugins:
  # Running `npm test` will run tests directly against the Lambda handler.
  - serverless-mocha-plugin

custom:
  apollo:
    # This is the Engine API key.  Create yours at:
    #  https://engine.apollographql.com/
    engineApiKey: !YOUR_KEY_HERE!

# This is the custom name of your service.  You can run multiple services
# however should use a different name, within regions.
service: apollo-engine-simple

provider:
  # This only supports AWS at the moment!
  name: aws

  # AWS only supports Node 6 at the moment!
  runtime: nodejs6.10

  # AWS currently only supports Fargate in us-east-1, but this is expected
  # to change, as is typical with Amazon's "land-and-expand" deployment.
  region: us-east-1

  # Due to our need to use both AWS-style and Serverless-style variables,
  # which share the same format, we need to use a different style of
  # variable within this Serverless project!  Hopefully this can be
  # avoided once this is built into a Serverless plugin!
  variableSyntax: "\\%{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}"
  environment:
    # This demonstrates exposing particular aspects of the newly created
    # environment to the Lamdba resolver itself.  In this case, this
    # URL allows the Lambda to talk back with the Engine Proxy,
    # which is used by the `engineHealth` query.
    ENGINE_PROXY_URL: '%{file(apollo/helpers.yml):engineProxyUrl}'

functions:
  # This resolver code lives in the similarly named path and export!
  query:
    handler: functions/query/index.default

resources:
  # This implements a simple, public-only network with no private resources.
  # Other options can be added in the future.
  - '%{file(apollo/engine-simple.yml):resources}'

  # This allows the stack to print the new URL of the stack so you can
  # start playing with it as soon as it comes up!
  - Outputs:
      ExternalUrl:
        Description: The url of the Engine proxy, ready to serve!
        Value: '%{file(apollo/helpers.yml):engineProxyUrl}'
